services:
  bugsnag-mattermost-hooks:
    image: goodmagma/bugsnag-mattermost-hooks:latest
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      APP_DEBUG: false
      MATTERMOST_URL: https://mattermost.example.com