services:
  mattermost_hooks:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      MATTERMOST_URL: https://mattermost.example.com
    volumes:
      - .:/app
